version: "3.9"

services:
  db:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: PostgresDb
    ports:
      - "5432:5432"  
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
